# NOTE: This file comes from `savi-lang/base-standard-library`
#
# This workflow is responsible for running checks on pushed commits.
#
# The workflow is triggered on pull requests and pushes to the main branch.
# Pull requests are checked on a merge branch, not on the pull request branch.
# It is also triggered daily to check for regressions against the latest
# version of the Savi language and the latest versions of library dependencies.

name: library-check

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 10 * * *" # daily at 10:00 UTC

jobs:
  # Run the `spec` binary for this library.
  spec:
    if: github.repository != 'savi-lang/base-standard-library' # skip base repo
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: savi-lang/action-install@v1.0.0
      - run: savi deps update --for spec
      - run: savi run spec

  # Check formatting of all files in the repository.
  format:
    if: github.repository != 'savi-lang/base-standard-library' # skip base repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: savi-lang/action-install@v1.0.0
      - run: savi format --check

  ##
  # NOTE: The following jobs do not come from `savi-lang/base-standard-library`.
  #
  # Add any custom jobs you need below this comment.
  # The area above this comment is reserved for future standard jobs.

  # Run some integration tests using a binary that prints ticks on a timer.
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: savi-lang/action-install@v1.0.0
      - run: savi deps update --for integration-ticker
      - run: savi build integration-ticker

      - name: Check timer ticks output
        run: |
          bin/integration-ticker | tee /tmp/integration-ticker-output
          printf "number of ticks: "
          wc -l < /tmp/integration-ticker-output | grep 50
          printf "number of accurate ticks: "
          cat /tmp/integration-ticker-output | grep 100 | wc -l | grep 50
